version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nette-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/var/www/html
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/app_db"

  db:
    image: mysql:9.1
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql